### ISSUE TITLE
FACC returned non-unicode character

### ISSUE THREAD

**Issue by Huji** [PersianWikipedia/fawikibot#1]
See [this edit](https://fa.wikipedia.org/w/index.php?title=%D8%B1%DB%8C%D8%B2%D9%BE%D8%B1%D8%AF%D9%87&diff=prev&oldid=18666232), which happened when I ran fa_cosmetic_changes_core.py on that page.

**Comment by reza1615** [comment]
` text=re.sub(ur'\[{2}([^\|]+)\|\1\]{2}',u'[[\1]]',text)`
does this edit I tested this regex at [here](https://regex101.com/) and it works fine. please deactive this part of code and test it again
